### ISSUE TITLE
`modprobe.d` method is not recommended

### ISSUE THREAD

**Issue by foxjaw** [korvahannu/arch-nvidia-drivers-installation-guide#14]
https://github.com/korvahannu/arch-nvidia-drivers-installation-guide?tab=readme-ov-file#option-a-for-driver-versions--545  
`modeprobe.d` drm setting is not recommended, as early kms loading requires boot parameters to be set either in `grub` or `systemd-boot` (depending on what one uses). Otherwise you'll not get consistent results.  
https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting  
Please use kernel boot parameters instead of modprobe.d configs. The difference is  
`nvidia_drm.modeset=1` for kernel instead of `options nvidia-drm modeset=1` for modprobe.d

**Comment by korvahannu** [comment]
Hi! Are you saying that option B. should be suitable for everyone? I had a discussion with a couple of people about it and the Arch wiki is a bit ambiguous about it. As per my understanding, the wiki instructs using the option A. for driver versions >= 545.

Related:
https://github.com/korvahannu/arch-nvidia-drivers-installation-guide/issues/6

Thanks,
Hannu

**Comment by korvahannu** [comment]
Ah I see! I may revert the changes then. I am unable to test option A myself. Thanks for letting me know.

**Comment by mataha** [comment]
> For me it doesn't. modprobe configs don't reinitialise on resumption. But strangely boot parameters do. And this is still an issue on > v545.

Chiming in to mention I've faced the same issue - updating GRUB configuration worked like a charm.

**Comment by korvahannu** [comment]
Issue now addressed on commit 4c3f36a49d3cb07c3f85574134d72883f5de439b
