### ISSUE TITLE
My graphics card is not listed here

### ISSUE THREAD

**Issue by daV1304** [korvahannu/arch-nvidia-drivers-installation-guide#15]
hello! i have a GeForce 310M in my laptop and i want to install drivers, does the 400/500/600 drivers work for my graphics card?

**Comment by korvahannu** [comment]
Hi! 

You may use the packages nvidia-340xx-dkms, nvidia-340xx-utils, and lib32-nvidia-340xx-utils. Please note, that these are legacy drivers that are no longer actively supported, and thus it might be easier to just use the nouveau driver (according to the wiki). If you try out the legacy drivers, it would be interesting to hear what your experiences are.

More information here:
https://wiki.archlinux.org/title/NVIDIA#Unsupported_drivers

-Hannu
