### ISSUE TITLE
Drivers for gtx 1080

### ISSUE THREAD

**Issue by omnigenous** [korvahannu/arch-nvidia-drivers-installation-guide#17]
I'm a bit confused with this guide, on [Nvidia's site](https://www.nvidia.com/Download/index.aspx) when I select my gtx 1080 I get to [this](https://www.nvidia.com/Download/driverResults.aspx/217147/) page which recommends `535` version of drivers while `nvidia` package is on `545` right now.

Should I still install `nvidia` package or `nvidia-535xx-dkms`  instead (I don't think `nvidia-535xx` exists)?

**Comment by korvahannu** [comment]
Hi! You can try installing the dkms package if you want, but for your pascal graphics card the _nvidia_ -package is the recommended one.

Br., Hannu
