### ISSUE TITLE
Not complete yet.

### ISSUE THREAD

**Issue by gnireorb** [korvahannu/arch-nvidia-drivers-installation-guide#19]
Related to systemd

[arch-nvidia-drivers-installation-guide](https://github.com/korvahannu/arch-nvidia-drivers-installation-guide)
`nvidia-drm.modeset=1`

https://wiki.hyprland.org/Nvidia/
`nvidia_drm.modeset=1`

Also don't forget to add to hyprland.conf
`env = WLR_NO_HARDWARE_CURSORS,1`

**Comment by korvahannu** [comment]
Hi! Both of the options, ```nvidia-drm.modeset=1``` and ```nvidia_drm.modeset=1```, work fine and you can choose one or the other. As for hyprland, I may consider adding some information regarding it in the future if issues arise, but I want this guide to remain as generic and as simple as possible for now.

Br.,
Hannu

**Comment by gnireorb** [comment]
Kiddos will have no mouse cursor without setting WLR_NO_HARDWARE_CURSORS to 1.

Follow up the Hyprland guide to Nvidia.
