### ISSUE TITLE
Add nvidia_drm.fbdev=1

### ISSUE THREAD

**Issue by cblinq** [korvahannu/arch-nvidia-drivers-installation-guide#26]
Could you kindly also add nvidia_drm.fbdev=1 to early boot options?

Required in [kernel 6.11](https://wiki.archlinux.org/title/NVIDIA#fbdev)

**Comment by korvahannu** [comment]
Hello @cblinq! Thanks for the heads up. Can you do a quick review of [the pull request regarding this?](https://github.com/korvahannu/arch-nvidia-drivers-installation-guide/pull/27)
