### ISSUE TITLE
nvidia_drm  or nvidia-drm?

### ISSUE THREAD

**Issue by Firestar-Reimu** [korvahannu/arch-nvidia-drivers-installation-guide#28]
I see on archwiki it use `nvidia_drm`, underscore, not hyphen

https://wiki.archlinux.org/title/NVIDIA

![image](https://github.com/user-attachments/assets/8d9803df-cf5d-4151-9e44-d45598d754a7)

**Comment by korvahannu** [comment]
Hi! Both nvidia_drm and nvidia-drm work fine.
