### ISSUE TITLE
Many thanks!

### ISSUE THREAD

**Issue by SlimJim192** [korvahannu/arch-nvidia-drivers-installation-guide#5]
Many thanks for this, 

Arch wiki is great but I couldn't figure out how to set the kernel mode parameters, feel like they kind of glossed over that, but I guess it's something I'm supposed to know ha.

Linux noob throwing himself in the deepend here.

Have you considered submitting this to the arch wiki? I assume theyd accept community contribututions!

**Comment by korvahannu** [comment]
Hi!

Thanks for the comment, I appreciate it 😊. Most of the information in this guide comes from the Arch Linux wiki. Even the part about DRM kernel mode setting.

In my opinion, Arch Wiki can be a bit challenging to read. When I used Arch for the first time I had trouble getting the NVIDIA drivers to work. This guide attempts to provide an easy-to-read instructions for the task that beginners can follow.

That being said, I don't this guide would offer anything new to Arch Wiki as this contains the same information just organized differently. I'm sure they have their standards and rules on how to organize the contents of articles there.

Best regards,
Hannu K
