### ISSUE TITLE
Driver version >= 545

### ISSUE THREAD

**Issue by matiux** [korvahannu/arch-nvidia-drivers-installation-guide#6]
According to the [WIKI](https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting), driver  >= 545 needs a l slightly different approach. Instead of passing option nvidia_drm.modeset=1 through kernel parameters, create a `etc/modprobe.d/nvidia.conf` file with this content
```
blacklist nouveau

options nvidia_drm modeset=1 fbdev=1
```
Then:
mkinitcpio -P

What do you think about this?

**Comment by korvahannu** [comment]
Hi,

Thanks! Good catch. I will see how to incorporate this into the guide 👍

- Hannu

**Comment by korvahannu** [comment]
I have created an initial version of this enhancement on a new branch. Any thoughts on it? The wget -command is wrong in the branch, but it will be "fixed" when it gets merged. I can not verify that it works at the moment as I no longer have an NVIDIA computer 😑

https://github.com/korvahannu/arch-nvidia-drivers-installation-guide/tree/driver-version-oq-545

**Comment by ShadowKing345** [comment]
Hello, small thing I thought to bring up with the branch you linked. It seems I needed to do both option A and B since I have newer drivers and boot using grub. If I did not my displays would not be recognized correctly.

**Comment by korvahannu** [comment]
Interesting. The official wiki states that only option A would be required for driver versions >= 545. Did you try first with only option A? Or have you tried with only option B? Any information you can give helps a lot. Thanks!

**Comment by matiux** [comment]
For me works the option for driver >= 545

**Comment by ShadowKing345** [comment]
A bit late, but I did try with option A by itself first. It resulted in the desktop manager (kde plasma) not being able to detect the any of my displays properly. Once I did option A and B for the grub config the displays were being picked up correctly. Not sure if the wiki implied you needed both or not but I got the impression I needed both.
