### ISSUE TITLE
Module not found: nvidia, nvidia-x,)

### ISSUE THREAD

**Issue by hammyexe** [korvahannu/arch-nvidia-drivers-installation-guide#9]
when i do, sudo mkinitcpio -P
i get all the modules i was told to add in the mkinitcpio config says modules not found.
i have a rtx 2070 super and i used pacman -S nvidia nvidia utils.

**Comment by korvahannu** [comment]
Hi! Follow what the error said and check that you have installed everything correctly. For example, what kernel are you using? For lts-kernels the package is nvidia-lts, and for other kernels its nvidia-dkms.

Yt., Hannu

**Comment by hammyexe** [comment]
I am using linux-arch latest kernel
also if i dont use the nomodeset kernel parameter i get an infinite black screen on boot.

**Comment by korvahannu** [comment]
Hi! Did you figure this out yet? If you can find what was wrong I will see if I can incorporate it into this guide so others wont face the same issue.

**Comment by korvahannu** [comment]
If you want you can try using this branch https://github.com/korvahannu/arch-nvidia-drivers-installation-guide/tree/driver-version-oq-545 and see if that helps. Especially the part "For GRUB users with driver version < 545" could have something to do with it.
